version: "3.1"

services:
    plattgpt:
        container_name: plattgpt
        image: plattgpt
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"